### ISSUE TITLE
Long Headers

### ISSUE THREAD

**Issue by lde-alen** [hardyrafael17/norminette42.nvim#1]
could we have an upgrade for long headers if it isn't too time consuming?
if not when I am done wiith cub3d I can work on it and send a pull request

**Comment by hardyrafael17** [comment]
Sure, I can give it some time, I would need to understand well what the request for Long Headers is. Let me know.

**Comment by lde-alen** [comment]
So basically for example on my campus header emails are "intralogin@student.42abudhabi.ae", this usually messes up the header spaces and also in your plugging it does not allow me to put it. So if I set my git global email to any of these it throws me an error and asks me to make sure I am using the short email for the header

**Comment by hardyrafael17** [comment]
I see, can you give me an example of how this log email should look in a header file? (Or something I can do without an example, is to leave the email field empty so that users can manually add it)
